name: Build and deploy main
on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-and-deploy-main:
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install vercel globally
        run: pnpm add -g vercel

      - name: Install dependencies
        run: pnpm install

      - name: Build the server
        run: pnpm build

      - name: Deploy to vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
