name: Test the project

on: [push, pull_request]

jobs:
  test-project:
    runs-on: ubuntu-latest

    env:
      PORT: 3000
      HOST: '127.0.0.1'
      FAKE_USER_AMOUNT: 100
      FAKE_POST_AMOUNT: 200
      FAKE_COMMENT_AMOUNT: 400
      ACCESS_TOKEN_SECRET: fake_access_secret
      REFRESH_TOKEN_SECRET: fake_access_secret

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Unit test the project
        run: pnpm test:unit:ci

      - name: E2E test the project
        run: pnpm test:e2e:ci
