name: Test the project

on:
  push:
  pull_request:
    branches: []

jobs:
  test-project:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Unit test the project
        run: pnpm test:unit:ci

      - name: E2E test the project
        run: pnpm test:e2e:ci
